baseURL = "https://andrewpjackson.com/"
languageCode = "en-us"
title = "andrewpjackson.com"
googleAnalytics = "UA-60119459-2"
canonifyURLs = true
theme = beautifulhugo
[Params]
  commit = "https://github.com/<username>/<siterepo>/tree/"
