version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.21
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: ""
          command: go get -v github.com/JacksonConsulting/s3up
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/src/
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/src/public --allow-hash-href --check-html --empty-alt-ignore
      - add_ssh_keys
      - deploy:
          s3up:
            branch: master
            commands:
              - s3up -source=~/project/src/public/ -bucket=$BUCKET
